server:
  type: default
  #http://localhost:8081/admin
  adminContextPath: /admin
  #http://localhost:8080/app/hello/
  #http://localhost:8080/app/static/index.html
  applicationContextPath: /app
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

  #If want to use our own exception mappers
  registerDefaultExceptionMappers: false

  #Disable the requestLog on console
  requestLog:
    appenders: []

logging:
  level: INFO
  loggers:
    bszeti.dropwizard.dwexample: DEBUG

tempDir: /tmp
greetings:
 - lang: en
   pattern: Hello %s!
 - lang: es
   pattern: ¡Hola %s!
 - lang: hu
   pattern: Szia %s!
